### ISSUE TITLE
`-A: invalid option`

### ISSUE THREAD

**Issue by little-flag** [MunifTanjim/luver#7]
Hi. I've installed luver by cloning and then sourcing `luver.plugin.zsh` (on macOS 13.2).

When I try to run `luver help` I get this message:

```
/Users/username/.local/share/luver/self/bin/command/help: line 157: local: -A: invalid option
local: usage: local name[=value] ...
```
Am I doing something wrong or is there a bug?

**Comment by MunifTanjim** [comment]
What is the version of your bash shell? `bash --version`.

Can you try upgrading it?

**Comment by little-flag** [comment]
> Can you try upgrading it?

Yes, that worked. Sorry, I should have tried that!

Apple having abandoned bash for zsh means they have only an ancient version of bash installed by default. Easy to add a proper version though.

**Comment by MunifTanjim** [comment]
https://github.com/MunifTanjim/luver/commit/4de334ec84242e4e7a47432c05b71e0946f7f23b

Mentioned the required bash version in README.
