### ISSUE TITLE
LuaRocks packages not in `PATH`, how to add?

### ISSUE THREAD

**Issue by thehunmonkgroup** [MunifTanjim/luver#8]
I thought Luver would just handle adding LuaRocks packages to `PATH`, but that does not seem to be so.

How do I accomplish that?

```
[:~] $ luver list
5.3.6 default *
[:~] $ lua -v
Lua 5.3.6  Copyright (C) 1994-2020 Lua.org, PUC-Rio
[:~] $ luarocks list

Rocks installed for Lua 5.3
---------------------------

lua-cjson
   2.1.0.10-1 (installed) - /home/hunmonk/.local/share/luver/lua-versions/5.3.6/installation/lib/luarocks/rocks-5.3

[:~] $ lua
Lua 5.3.6  Copyright (C) 1994-2020 Lua.org, PUC-Rio
> local cjson = require "cjson"
stdin:1: module 'cjson' not found:
        no field package.preload['cjson']
        no file '/usr/local/share/lua/5.3/cjson.lua'
        no file '/usr/local/share/lua/5.3/cjson/init.lua'
        no file '/usr/local/lib/lua/5.3/cjson.lua'
        no file '/usr/local/lib/lua/5.3/cjson/init.lua'
        no file './cjson.lua'
        no file './cjson/init.lua'
        no file '/usr/local/lib/lua/5.3/cjson.so'
        no file '/usr/local/lib/lua/5.3/loadall.so'
        no file './cjson.so'
stack traceback:
        [C]: in function 'require'
        stdin:1: in main chunk
        [C]: in ?
>
```

**Comment by MunifTanjim** [comment]
`luver` is just a toolchain version manager.

What you're looking for are these commands:

- `luarocks path` - https://github.com/luarocks/luarocks/wiki/path
- `luarocks init`

You can find more about them in LuaRocks' documentation.

You can do this:

```sh
eval $(luarocks path)
```

To update `LUA_PATH` and `PATH` environment variable for the current `luarocks`.

Then you can run `lua` and `require()` installed packages.

**Comment by thehunmonkgroup** [comment]
@MunifTanjim thanks for the tip!

One lingering question: since `luver` manages multiple Lua versions, it would make sense to run that `eval "$(luarocks path --bin)"` command whenever `luver` switches to a new Lua environment.

Is there some kind of mechanism in `luver` that I can hook into to run that command *after* `luver` switches to the new environment?

**Comment by MunifTanjim** [comment]
It's a bit trickier than that. You can't just keep doing `eval $(luarocks path)` each time luver changes the version. Once `LUA_PATH` and `LUA_CPATH` are set, `luarocks` will keep using those values... so the next time you run `luarocks path` it'll output the same value.

So your best bet is to open a new fresh shell, change the lua version using `luver use` then run `eval $(luarocks path)`.

You can check it yourself:


```sh
luver use 5.3.6
lua -v
luarocks --version
luarocks path

eval $(luarocks path)

luver use 5.1.5
lua -v
luarocks --version
luarocks path
```

**Comment by MunifTanjim** [comment]
You can also create a shell function if you want:

```sh
function lua-repl() {
  LUA_PATH=$(luarocks path --lr-path) LUA_CPATH=$(luarocks path --lr-cpath) lua
}
```

Put that in your shell config (`.bashrc` or `.zshrc`). And then you can run `lua-repl`.
